### ISSUE TITLE
All Media Not Showing Up on Website

### ISSUE THREAD

**Issue by SONICTHEHEDGEHOG19921124** [kurozenzen/r34-react#71]
So, Um...when I went onto the website, I was trying to search up videos, but when I searched it up, nothing showed up.
I am curently using a Chromebook
This has been happening for a while
PLZ HELP!!!!
![Screenshot 2022-12-29 12 16 29 PM](https://user-images.githubusercontent.com/121632805/209987079-e32d8e9b-57ce-4b5c-a9da-10c4398bc65d.png)

**Comment by kurozenzen** [comment]
Hey, sorry about this. I had trouble with my APIs for a while. It should all be resolved now though.

Let me know if there is still something broken :)

**Comment by SONICTHEHEDGEHOG19921124** [comment]
I know that that comment i made is very dated...but it still doesn't work
after janruary 10th.
